import {
  BadgeCheck,
  BarChart3,
  Bot,
  MessagesSquare,
  Banknote,
  Bell,
  BookOpen,
  BookOpenCheck,
  CalendarClock,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileStack,
  FileText,
  HeartHandshake,
  History,
  IdCard,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  ListChecks,
  NotebookPen,
  GraduationCap,
  PlayCircle,
  Receipt,
  School,
  ScanLine,
  Settings,
  ShieldAlert,
  TrendingUp,
  UserRound,
  UserRoundCog,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { NavIcon as NavIconName } from "@/config/navigation";

const ICONS: Record<NavIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  account: UserRound,
  students: GraduationCap,
  enrollments: ClipboardList,
  guardians: Users,
  classes: School,
  structure: Layers,
  forms: ListChecks,
  timetable: CalendarClock,
  attendance: ClipboardCheck,
  grades: NotebookPen,
  reportCards: FileText,
  staff: UserRoundCog,
  staffAttendance: BadgeCheck,
  kiosk: ScanLine,
  lessons: BookOpenCheck,
  finance: Wallet,
  portal: HeartHandshake,
  audit: History,
  settings: Settings,
  notifications: Bell,
  subjects: BookOpen,
  documents: FileStack,
  badges: IdCard,
  payments: CreditCard,
  invoices: Receipt,
  expenses: Banknote,
  revenue: TrendingUp,
  overdue: ShieldAlert,
  users: UsersRound,
  roles: KeyRound,
  demo: PlayCircle,
  school: School,
  year: CalendarRange,
  templates: LayoutTemplate,
  reports: BarChart3,
  assistant: Bot,
  communication: MessagesSquare,
};

export function NavIcon({ name, className }: { name: NavIconName; className?: string }) {
  const Icon = ICONS[name];
  return <Icon className={className} aria-hidden />;
}
