/**
 * Textes du site officiel NeoScool (français et anglais).
 * Règle : chaque affirmation correspond à une fonctionnalité réellement présente
 * dans le logiciel (voir docs/site-web/architecture.md). Aucun chiffre, client,
 * partenariat, certification ni intégration nationale n'est inventé.
 */

export type Locale = "fr" | "en";

export const CAPTURE = (name: string) => `/site/captures/${name}.webp`;

const frDict = {
  meta: {
    title: "NeoScool — La gestion quotidienne de votre établissement, dans un seul écosystème",
    description:
      "Plateforme de gestion pour établissements scolaires, universités et centres de formation : élèves, notes, bulletins, présences, finances, portails et pilotage dans un seul écosystème.",
  },
  nav: {
    solutions: "Solutions",
    features: "Fonctionnalités",
    countries: "Pays",
    discover: "NeoScool Discover",
    discoverHint: "Trouver un établissement",
    opportunities: "NeoScool Opportunities",
    opportunitiesHint: "Emplois, stages, répétiteurs",
    pricing: "Tarifs",
    contact: "Contact",
    login: "Se connecter",
    demo: "Demander une démo",
    menu: "Menu",
    close: "Fermer",
    language: "Langue",
  },
  sectorsNav: {
    school: "Scolaire",
    university: "Université",
    training: "Formation professionnelle",
  },
  hero: {
    eyebrow: "Plateforme de gestion d'établissement",
    title1: "Votre établissement.",
    title2: "Un seul écosystème.",
    subtitle: "Élèves, notes, bulletins, présences, paiements et lien avec les familles : NeoScool réunit la gestion de votre école, université ou centre de formation dans un seul logiciel en ligne.",
    discover: "Découvrir NeoScool",
    software: "Voir le logiciel",
    demo: "Demander une démonstration",
    captionDemo: "Captures réelles du logiciel, sur l'établissement de démonstration (données fictives).",
  },
  connected: {
    eyebrow: "Tous connectés",
    title: "Une seule plateforme pour connecter les acteurs, les données et les opérations quotidiennes.",
    core: "NeoScool",
    actors: ["Direction", "Enseignants", "Élèves", "Parents", "Comptabilité", "Administration"],
  },
  video: {
    eyebrow: "En action",
    title: "Découvrez NeoScool en action.",
    subtitle: "Des vidéos courtes pour voir le logiciel au travail, module par module.",
    soon: "La vidéo de présentation est en préparation.",
    soonHint: "En attendant, demandez une démonstration : nous vous montrons le logiciel en direct.",
    play: "Lire la vidéo",
    topics: {
      school: "Module scolaire",
      university: "Université",
      training: "Formation professionnelle",
      badge: "Smart Badge",
      ai: "Assistant IA",
      steering: "Pilotage",
      portals: "Portails",
      other: "Présentation",
    },
  },
  sectors: {
    eyebrow: "Secteurs",
    title: "Une plateforme pour différents environnements éducatifs.",
    subtitle: "Chaque module parle la langue de son établissement : élève, étudiant ou apprenant ; classe, promotion ou session.",
    more: "Découvrir",
    school: {
      title: "Scolaire",
      tagline: "Maternelle, primaire, collège, lycée",
      items: ["Élèves et familles", "Classes et niveaux", "Enseignants", "Emploi du temps", "Présences", "Notes et bulletins", "Finances", "Documents", "Communication", "Portails parents et élèves"],
    },
    university: {
      title: "Université",
      tagline: "Universités, instituts, écoles supérieures",
      items: ["Étudiants", "Facultés et départements", "Filières et parcours", "Cycles, niveaux et semestres", "UE et matières", "Crédits ECTS", "Sessions d'examen et rattrapage", "Délibérations", "Relevés et diplômes", "Stages, mémoires et soutenances"],
    },
    training: {
      title: "Formation professionnelle",
      tagline: "Centres de formation professionnelle et technique",
      items: ["Apprenants", "Formations", "Sessions et promotions", "Groupes", "Modules", "Formateurs", "Présences", "Évaluations", "Compétences", "Attestations et relevés"],
    },
  },
  flow: {
    eyebrow: "Module scolaire",
    title: "Tout est relié, de l'inscription à l'historique.",
    subtitle: "Chaque étape alimente la suivante : rien n'est ressaisi.",
    steps: ["Inscription", "Élève", "Classe", "Emploi du temps", "Cours", "Présence", "Évaluation", "Note", "Bulletin", "Parent", "Portail", "Historique"],
    details: [
      "Formulaire d'inscription personnalisable, remises, dossier créé automatiquement.",
      "Dossier complet : identité, famille, documents, parcours.",
      "Affectation à la classe et au niveau de l'année scolaire.",
      "Grille par classe et par enseignant, créneaux et salles.",
      "L'enseignant retrouve ses cours du jour.",
      "Appel en quelques touches, justifications suivies.",
      "Évaluations par matière, coefficients, périodes.",
      "Saisie en grille ou import Excel/CSV, validation.",
      "Moyennes, rangs, appréciations et PDF avec QR de vérification.",
      "Les familles sont informées.",
      "Notes, présences, finances et documents sur le portail.",
      "Résultats annuels, passage d'année et archives conservés.",
    ],
  },
  actors: {
    eyebrow: "Les acteurs",
    title: "Chacun son espace. Un seul écosystème.",
    list: [
      { key: "direction", name: "Direction", text: "Pilotez votre établissement.", capture: "s-dashboard" },
      { key: "teacher", name: "Enseignant", text: "Organisez vos cours et suivez vos élèves.", capture: "s-mes-cours" },
      { key: "parent", name: "Parent", text: "Suivez la scolarité de vos enfants.", capture: "s-portail" },
      { key: "student", name: "Élève", text: "Accédez à votre parcours scolaire.", capture: "s-portail-notes" },
      { key: "accountant", name: "Comptable", text: "Suivez les paiements et les finances.", capture: "s-finances" },
      { key: "admin", name: "Administration", text: "Centralisez les opérations de votre établissement.", capture: "s-eleves" },
    ],
  },
  journey: {
    eyebrow: "Saisie unique",
    title: "Une information saisie une fois. Plusieurs utilisations.",
    source: "Donnée élève",
    stops: ["Dossier", "Classe", "Présence", "Notes", "Bulletin", "Portail", "Statistiques", "Archives", "Export"],
  },
  features: {
    eyebrow: "Fonctionnalités",
    title: "Plus qu'un logiciel de gestion.",
    list: [
      { key: "badge", title: "Smart Badge", text: "Cartes et badges avec QR code, tablette de pointage du personnel, message vocal à l'arrivée." },
      { key: "ai", title: "Assistant IA", text: "Questions en langage courant sur les données que vous avez le droit de voir, lorsque l'assistant est activé." },
      { key: "notifications", title: "Notifications", text: "Dans l'application et sur téléphone ; e-mail, SMS et WhatsApp selon les canaux configurés." },
      { key: "automation", title: "Automatisations", text: "Relances d'impayés, rappels et messages automatiques programmés." },
      { key: "offline", title: "Mode hors ligne", text: "L'appel et le pointage continuent sans réseau, puis se synchronisent." },
      { key: "documents", title: "Documents vérifiables", text: "Bulletins, reçus, attestations et cartes en PDF, avec QR code de vérification." },
      { key: "stats", title: "Statistiques", text: "Tableaux de bord et rapports exportables, par établissement." },
      { key: "audit", title: "Journal d'audit", text: "Chaque opération sensible est tracée et ne peut pas être modifiée." },
      { key: "security", title: "Sécurité", text: "Rôles, permissions et séparation stricte des établissements." },
    ],
  },
  badge: {
    eyebrow: "Smart Badge",
    title: "Un badge, un scan, un enregistrement fiable.",
    note: "Le scan enregistre un pointage d'arrivée ou de départ. La présence en cours reste validée par l'appel de l'enseignant.",
    steps: ["Personne", "Badge", "Scan", "Identification", "Établissement", "Rôle", "Autorisations", "Événement", "Enregistrement"],
  },
  offline: {
    eyebrow: "Hors ligne",
    title: "Le réseau coupe ? Le travail continue.",
    note: "Concerne l'appel et le pointage : les opérations sont mises en attente sur l'appareil, sans données personnelles, puis envoyées au retour du réseau.",
    steps: ["En ligne", "Perte de connexion", "Mode hors ligne", "Travail continu", "Opérations en attente", "Connexion restaurée", "Synchronisation", "Confirmation"],
  },
  security: {
    eyebrow: "Sécurité",
    title: "Vos données. Vos accès. Vos règles.",
    list: [
      { title: "Rôles et permissions", text: "Chaque personne n'accède qu'à ce que son rôle autorise, contrôlé côté serveur." },
      { title: "Établissements séparés", text: "Les données de chaque établissement sont isolées au niveau de la base de données." },
      { title: "Historique et audit", text: "Journal inaltérable des opérations : qui, quoi, quand." },
      { title: "Contrôle des accès", text: "Double authentification, sessions visibles et révocables, verrouillage après échecs." },
    ],
  },
  data: {
    eyebrow: "Import et export",
    title: "Vos données restent exploitables.",
    importTitle: "Importer",
    importSteps: ["Excel / CSV", "Analyse", "Correspondance des colonnes", "Validation", "NeoScool"],
    exportTitle: "Exporter",
    exportFormats: ["XLSX", "CSV", "PDF", "PNG"],
    exportNote: "Formats disponibles aujourd'hui : Excel (XLSX) et CSV pour les listes et rapports, PDF pour les documents, PNG pour les cartes.",
  },
  multi: {
    eyebrow: "Multi-établissements",
    title: "Une organisation. Des espaces séparés.",
    org: "Organisation",
    spaces: ["Établissement A", "Établissement B", "Établissement C"],
    points: ["Une seule plateforme pour le groupe", "Des données séparées par établissement", "Des utilisateurs avec leurs permissions dans chaque établissement", "Un enseignant peut travailler dans plusieurs établissements avec un seul compte"],
  },
  countries: {
    eyebrow: "International",
    title: "Pensé pour l'éducation en Afrique et au-delà.",
    subtitle: "Pays pris en charge par la configuration NeoScool : devise, langues, fuseau horaire, formats et paramètres scolaires adaptés à chaque contexte.",
    national:
      "NeoScool accompagne la gestion quotidienne de votre établissement. Il ne remplace pas les systèmes institutionnels et nationaux : les établissements continuent de les utiliser, et NeoScool peut faciliter la préparation, l'importation ou l'exportation des données par fichiers lorsque c'est prévu.",
    currency: "Devise",
    languages: "Langues",
    timezone: "Fuseau horaire",
    grading: "Notation",
    periods: "Périodes",
    structure: "Structure académique",
    context: "Contexte éducatif",
    systems: "Systèmes institutionnels concernés",
    systemsNote: "NeoScool fonctionne en complément de ces systèmes ; il ne les remplace pas.",
    availability: { configurable: "Configuration disponible", preparing: "En préparation", available: "Disponible" },
    periodLabels: { trimester: "Trimestres", semester: "Semestres" } as Record<string, string>,
    all: "Voir tous les pays",
    languageNames: { fr: "Français", en: "Anglais" } as Record<string, string>,
  },
  pricing: {
    eyebrow: "Tarifs",
    title: "Des offres adaptées à votre établissement.",
    subtitle: "Prix mensuels ou annuels, essai gratuit, sans engagement caché.",
    perMonth: "/ mois",
    perYear: "/ an",
    trial: (days: number) => `${days} jours d'essai gratuit`,
    see: "Voir tous les tarifs",
    quote: "Besoin d'un devis ?",
    offer: "Offre en cours",
  },
  testimonials: { eyebrow: "Témoignages", title: "Ils utilisent NeoScool." },
  facts: [
    "Scolaire, université et formation professionnelle",
    "Sur ordinateur, tablette et téléphone",
    "Appel et pointage même sans connexion",
    "Données séparées et protégées par établissement",
  ],
  audience: {
    label: "Pour qui ?",
  },
  howItWorks: {
    eyebrow: "Comment ça marche",
    title: "Démarrer avec NeoScool, en trois étapes.",
    subtitle: "Pas d'installation : tout se passe en ligne, depuis un navigateur.",
    steps: [
      { title: "Créez votre établissement", text: "Ouvrez votre compte en ligne, choisissez votre type d'établissement et votre formule." },
      { title: "Configurez et importez", text: "Année scolaire, classes, matières et frais. Importez vos élèves depuis un fichier Excel ou CSV." },
      { title: "Travaillez au quotidien", text: "Appel, notes, bulletins et paiements. Les familles suivent tout depuis leur portail." },
    ],
    signup: "Créer mon établissement",
    demo: "Voir la démonstration en ligne",
  },
  ecosystem: {
    eyebrow: "L'écosystème NeoScool",
    title: "Au-delà de la gestion : deux services ouverts au public.",
    subtitle: "Les informations sont publiées par les établissements et les annonceurs eux-mêmes, et modérées par NeoScool.",
    discover: {
      title: "NeoScool Discover",
      text: "L'annuaire des établissements qui utilisent NeoScool : écoles, collèges, lycées, centres de formation et universités. Recherchez par pays, ville, type ou formation.",
      cta: "Trouver un établissement",
    },
    opportunities: {
      title: "NeoScool Opportunities",
      text: "Offres d'emploi des établissements, stages, cours à domicile, répétiteurs et services éducatifs. Annonces modérées.",
      cta: "Voir les annonces",
    },
  },
  finalCta: {
    title: "Votre établissement mérite un écosystème plus simple.",
    subtitle: "NeoScool vous accompagne dans la gestion quotidienne de votre établissement scolaire, universitaire ou centre de formation.",
    discover: "Découvrir NeoScool",
    demo: "Demander une démonstration",
    login: "Se connecter",
    signature: "La gestion quotidienne de votre établissement, autrement.",
  },
  footer: {
    product: "Produit",
    company: "NeoScool",
    legal: "Informations",
    help: "Aide et contact",
    terms: "Conditions générales",
    privacy: "Confidentialité",
    signup: "Créer mon établissement",
    rights: "Plateforme de gestion d'établissement.",
    follow: "Suivez-nous",
  },
  whatsapp: { label: "Parler à NeoScool", defaultMessage: "Bonjour NeoScool, je souhaite en savoir plus." },
  contact: {
    title: "Contact",
    subtitle: "Une question, un devis ou une démonstration ? Écrivez-nous : nous vous répondons rapidement.",
    demoTitle: "Voir NeoScool en action",
    demoSubtitle: "Demandez une démonstration : nous vous présentons le logiciel sur un établissement de démonstration.",
    kindContact: "Question ou devis",
    kindDemo: "Démonstration",
    name: "Nom et prénom",
    email: "E-mail",
    phone: "Téléphone",
    organization: "Établissement",
    orgType: "Type d'établissement",
    orgTypes: { school: "Établissement scolaire", university: "Université / institut", training: "Centre de formation", group: "Groupe d'établissements", other: "Autre" } as Record<string, string>,
    country: "Pays",
    message: "Message",
    send: "Envoyer",
    sent: "Merci ! Votre demande a bien été enregistrée. Nous vous recontactons rapidement.",
    direct: "Nous joindre directement",
    tryDemo: "Explorer la démonstration en ligne",
    signup: "Créer mon établissement (essai gratuit)",
    noContacts: "Nos coordonnées seront publiées prochainement ; utilisez le formulaire.",
    privacy: "Vos informations servent uniquement à répondre à votre demande.",
  },
  sectorPage: {
    back: "Tous les secteurs",
    screens: "Aperçu du logiciel",
    cta: "Voir ce module en démonstration",
  },
  countriesPage: {
    title: "Pays pris en charge par la configuration",
    subtitle: "NeoScool s'adapte au contexte de chaque pays. La liste s'enrichit depuis la console d'administration.",
  },
};

export type Dict = typeof frDict;

const enDict: Dict = {
  meta: {
    title: "NeoScool — Day-to-day management of your institution, in one ecosystem",
    description:
      "Management platform for schools, universities and training centres: students, grades, report cards, attendance, finance, portals and steering in one ecosystem.",
  },
  nav: {
    solutions: "Solutions",
    features: "Features",
    countries: "Countries",
    discover: "NeoScool Discover",
    discoverHint: "Find an institution",
    opportunities: "NeoScool Opportunities",
    opportunitiesHint: "Jobs, internships, tutors",
    pricing: "Pricing",
    contact: "Contact",
    login: "Sign in",
    demo: "Request a demo",
    menu: "Menu",
    close: "Close",
    language: "Language",
  },
  sectorsNav: { school: "Schools", university: "Universities", training: "Vocational training" },
  hero: {
    eyebrow: "Institution management platform",
    title1: "Your institution.",
    title2: "One ecosystem.",
    subtitle: "Students, grades, report cards, attendance, payments and contact with families: NeoScool brings the management of your school, university or training centre together in one online software.",
    discover: "Discover NeoScool",
    software: "See the software",
    demo: "Request a demo",
    captionDemo: "Real screenshots of the software, taken on the demo institution (fictitious data).",
  },
  connected: {
    eyebrow: "All connected",
    title: "One platform connecting the people, the data and the daily operations of your institution.",
    core: "NeoScool",
    actors: ["Management", "Teachers", "Students", "Parents", "Accounting", "Administration"],
  },
  video: {
    eyebrow: "In action",
    title: "See NeoScool in action.",
    subtitle: "Short videos showing the software at work, module by module.",
    soon: "The presentation video is being prepared.",
    soonHint: "In the meantime, request a demo: we will show you the software live.",
    play: "Play video",
    topics: {
      school: "School module",
      university: "University",
      training: "Vocational training",
      badge: "Smart Badge",
      ai: "AI assistant",
      steering: "Steering",
      portals: "Portals",
      other: "Overview",
    },
  },
  sectors: {
    eyebrow: "Sectors",
    title: "One platform for different educational environments.",
    subtitle: "Each module speaks its institution's language: pupil, student or learner; class, cohort or session.",
    more: "Discover",
    school: {
      title: "Schools",
      tagline: "Nursery, primary, lower and upper secondary",
      items: ["Pupils and families", "Classes and levels", "Teachers", "Timetable", "Attendance", "Grades and report cards", "Finance", "Documents", "Communication", "Parent and pupil portals"],
    },
    university: {
      title: "Universities",
      tagline: "Universities, institutes, higher education schools",
      items: ["Students", "Faculties and departments", "Programmes and tracks", "Cycles, levels and semesters", "Teaching units and courses", "ECTS credits", "Exam and resit sessions", "Deliberations", "Transcripts and diplomas", "Internships, theses and defences"],
    },
    training: {
      title: "Vocational training",
      tagline: "Vocational and technical training centres",
      items: ["Learners", "Programmes", "Sessions and cohorts", "Groups", "Modules", "Trainers", "Attendance", "Assessments", "Competencies", "Certificates and transcripts"],
    },
  },
  flow: {
    eyebrow: "School module",
    title: "Everything is linked, from enrolment to history.",
    subtitle: "Each step feeds the next: nothing is typed twice.",
    steps: ["Enrolment", "Pupil", "Class", "Timetable", "Lesson", "Attendance", "Assessment", "Grade", "Report card", "Parent", "Portal", "History"],
    details: [
      "Customisable enrolment form, discounts, file created automatically.",
      "Complete record: identity, family, documents, path.",
      "Assignment to the class and level of the school year.",
      "Grid per class and per teacher, slots and rooms.",
      "Teachers find their lessons of the day.",
      "Roll call in a few taps, excuses tracked.",
      "Assessments per subject, coefficients, terms.",
      "Grid entry or Excel/CSV import, validation.",
      "Averages, ranks, comments and PDF with verification QR code.",
      "Families are informed.",
      "Grades, attendance, finance and documents on the portal.",
      "Annual results, year rollover and archives kept.",
    ],
  },
  actors: {
    eyebrow: "The people",
    title: "Everyone has their space. One ecosystem.",
    list: [
      { key: "direction", name: "Management", text: "Steer your institution.", capture: "s-dashboard" },
      { key: "teacher", name: "Teacher", text: "Organise your lessons and follow your pupils.", capture: "s-mes-cours" },
      { key: "parent", name: "Parent", text: "Follow your children's schooling.", capture: "s-portail" },
      { key: "student", name: "Pupil", text: "Access your school record.", capture: "s-portail-notes" },
      { key: "accountant", name: "Accountant", text: "Track payments and finance.", capture: "s-finances" },
      { key: "admin", name: "Administration", text: "Centralise your institution's operations.", capture: "s-eleves" },
    ],
  },
  journey: {
    eyebrow: "Single entry",
    title: "Entered once. Used many times.",
    source: "Pupil data",
    stops: ["Record", "Class", "Attendance", "Grades", "Report card", "Portal", "Statistics", "Archives", "Export"],
  },
  features: {
    eyebrow: "Features",
    title: "More than management software.",
    list: [
      { key: "badge", title: "Smart Badge", text: "Cards and badges with QR codes, staff check-in tablet, voice message on arrival." },
      { key: "ai", title: "AI assistant", text: "Plain-language questions about the data you are allowed to see, when the assistant is enabled." },
      { key: "notifications", title: "Notifications", text: "In the app and on phones; e-mail, SMS and WhatsApp depending on configured channels." },
      { key: "automation", title: "Automation", text: "Overdue payment reminders, reminders and scheduled automatic messages." },
      { key: "offline", title: "Offline mode", text: "Roll call and check-in keep working without network, then synchronise." },
      { key: "documents", title: "Verifiable documents", text: "Report cards, receipts, certificates and cards as PDF, with a verification QR code." },
      { key: "stats", title: "Statistics", text: "Dashboards and exportable reports, per institution." },
      { key: "audit", title: "Audit log", text: "Every sensitive operation is recorded and cannot be altered." },
      { key: "security", title: "Security", text: "Roles, permissions and strict separation between institutions." },
    ],
  },
  badge: {
    eyebrow: "Smart Badge",
    title: "One badge, one scan, one reliable record.",
    note: "A scan records an arrival or departure check-in. Lesson attendance is still confirmed by the teacher's roll call.",
    steps: ["Person", "Badge", "Scan", "Identification", "Institution", "Role", "Permissions", "Event", "Record"],
  },
  offline: {
    eyebrow: "Offline",
    title: "Network down? Work goes on.",
    note: "Applies to roll call and check-in: operations are queued on the device, without personal data, then sent when the network returns.",
    steps: ["Online", "Connection lost", "Offline mode", "Work continues", "Operations queued", "Connection restored", "Synchronisation", "Confirmation"],
  },
  security: {
    eyebrow: "Security",
    title: "Your data. Your access. Your rules.",
    list: [
      { title: "Roles and permissions", text: "Everyone only accesses what their role allows, enforced on the server." },
      { title: "Separate institutions", text: "Each institution's data is isolated at database level." },
      { title: "History and audit", text: "Tamper-proof log of operations: who, what, when." },
      { title: "Access control", text: "Two-factor authentication, visible and revocable sessions, lockout after failed attempts." },
    ],
  },
  data: {
    eyebrow: "Import and export",
    title: "Your data stays usable.",
    importTitle: "Import",
    importSteps: ["Excel / CSV", "Analysis", "Column mapping", "Validation", "NeoScool"],
    exportTitle: "Export",
    exportFormats: ["XLSX", "CSV", "PDF", "PNG"],
    exportNote: "Formats available today: Excel (XLSX) and CSV for lists and reports, PDF for documents, PNG for cards.",
  },
  multi: {
    eyebrow: "Multi-institution",
    title: "One organisation. Separate spaces.",
    org: "Organisation",
    spaces: ["Institution A", "Institution B", "Institution C"],
    points: ["One platform for the whole group", "Data kept separate for each institution", "Users with their own permissions in each institution", "A teacher can work in several institutions with a single account"],
  },
  countries: {
    eyebrow: "International",
    title: "Designed for education in Africa and beyond.",
    subtitle: "Countries supported by NeoScool's configuration: currency, languages, time zone, formats and school settings adapted to each context.",
    national:
      "NeoScool supports the day-to-day management of your institution. It does not replace institutional or national systems: institutions keep using them, and NeoScool can help prepare, import or export data through files where this is planned.",
    currency: "Currency",
    languages: "Languages",
    timezone: "Time zone",
    grading: "Grading",
    periods: "Terms",
    structure: "Academic structure",
    context: "Educational context",
    systems: "Institutional systems concerned",
    systemsNote: "NeoScool works alongside these systems; it does not replace them.",
    availability: { configurable: "Configuration available", preparing: "In preparation", available: "Available" },
    periodLabels: { trimester: "Trimesters", semester: "Semesters" },
    all: "See all countries",
    languageNames: { fr: "French", en: "English" },
  },
  pricing: {
    eyebrow: "Pricing",
    title: "Plans suited to your institution.",
    subtitle: "Monthly or yearly prices, free trial, no hidden commitment.",
    perMonth: "/ month",
    perYear: "/ year",
    trial: (days: number) => `${days}-day free trial`,
    see: "See all pricing",
    quote: "Need a quote?",
    offer: "Current offer",
  },
  testimonials: { eyebrow: "Testimonials", title: "They use NeoScool." },
  facts: [
    "Schools, universities and vocational training",
    "On computer, tablet and phone",
    "Roll call and check-in even offline",
    "Data separated and protected per institution",
  ],
  audience: {
    label: "Who is it for?",
  },
  howItWorks: {
    eyebrow: "How it works",
    title: "Get started with NeoScool in three steps.",
    subtitle: "Nothing to install: everything runs online, from a web browser.",
    steps: [
      { title: "Create your institution", text: "Open your account online, choose your type of institution and your plan." },
      { title: "Set up and import", text: "School year, classes, subjects and fees. Import your students from an Excel or CSV file." },
      { title: "Work day to day", text: "Roll call, grades, report cards and payments. Families follow everything from their portal." },
    ],
    signup: "Create my institution",
    demo: "Try the online demo",
  },
  ecosystem: {
    eyebrow: "The NeoScool ecosystem",
    title: "Beyond management: two services open to the public.",
    subtitle: "Information is published by the institutions and advertisers themselves, and moderated by NeoScool.",
    discover: {
      title: "NeoScool Discover",
      text: "The directory of institutions using NeoScool: schools, colleges, high schools, training centres and universities. Search by country, city, type or programme.",
      cta: "Find an institution",
    },
    opportunities: {
      title: "NeoScool Opportunities",
      text: "Job offers from institutions, internships, home tutoring, tutors and educational services. Moderated listings.",
      cta: "See the listings",
    },
  },
  finalCta: {
    title: "Your institution deserves a simpler ecosystem.",
    subtitle: "NeoScool supports the day-to-day management of your school, university or training centre.",
    discover: "Discover NeoScool",
    demo: "Request a demo",
    login: "Sign in",
    signature: "Day-to-day management of your institution, differently.",
  },
  footer: {
    product: "Product",
    company: "NeoScool",
    legal: "Information",
    help: "Help and contact",
    terms: "Terms of use",
    privacy: "Privacy",
    signup: "Create my institution",
    rights: "Institution management platform.",
    follow: "Follow us",
  },
  whatsapp: { label: "Talk to NeoScool", defaultMessage: "Hello NeoScool, I would like to know more." },
  contact: {
    title: "Contact",
    subtitle: "A question, a quote or a demo? Write to us: we will get back to you quickly.",
    demoTitle: "See NeoScool in action",
    demoSubtitle: "Request a demo: we will present the software on a demo institution.",
    kindContact: "Question or quote",
    kindDemo: "Demo",
    name: "Full name",
    email: "E-mail",
    phone: "Phone",
    organization: "Institution",
    orgType: "Type of institution",
    orgTypes: { school: "School", university: "University / institute", training: "Training centre", group: "Group of institutions", other: "Other" },
    country: "Country",
    message: "Message",
    send: "Send",
    sent: "Thank you! Your request has been recorded. We will get back to you quickly.",
    direct: "Reach us directly",
    tryDemo: "Explore the online demo",
    signup: "Create my institution (free trial)",
    noContacts: "Our contact details will be published soon; please use the form.",
    privacy: "Your information is only used to answer your request.",
  },
  sectorPage: { back: "All sectors", screens: "Software preview", cta: "See this module in a demo" },
  countriesPage: {
    title: "Countries supported by the configuration",
    subtitle: "NeoScool adapts to each country's context. The list grows from the administration console.",
  },
};

export const DICTS: Record<Locale, Dict> = { fr: frDict, en: enDict };

/** Adresses des pages dans chaque langue. */
export const ROUTES = {
  home: { fr: "/", en: "/en" },
  contact: { fr: "/contact", en: "/en/contact" },
  countries: { fr: "/pays", en: "/en/countries" },
  pricing: { fr: "/tarifs", en: "/en/pricing" },
  school: { fr: "/secteurs/scolaire", en: "/en/sectors/school" },
  university: { fr: "/secteurs/universite", en: "/en/sectors/university" },
  training: { fr: "/secteurs/formation", en: "/en/sectors/training" },
} as const;

export type RouteKey = keyof typeof ROUTES;

export const route = (key: RouteKey, locale: Locale) => ROUTES[key][locale];

/** Captures réelles associées à chaque secteur (établissements de démonstration). */
export const SECTOR_CAPTURES = {
  school: ["s-dashboard", "s-emploi-du-temps", "s-notes", "s-bulletins-apercu", "s-finances", "s-portail"],
  university: ["u-dashboard", "u-structure", "u-resultats", "u-deliberation", "u-portail"],
  training: ["f-aujourdhui", "f-formations", "f-sessions", "f-competences", "f-statistiques"],
} as const;
